// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android; // Use Android config for Windows
      case TargetPlatform.linux:
        return android; // Use Android config for Linux
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9ZnAqbgLTijFoJkfCg1OUZybo5iM40c',
    appId: '1:905140505558:web:464c94181ff470b1613277',
    messagingSenderId: '905140505558',
    projectId: 'campus-companion-9691b',
    authDomain: 'campus-companion-9691b.firebaseapp.com',
    storageBucket: 'campus-companion-9691b.firebasestorage.app',
    measurementId: 'G-W5840Y9P5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsOb-DpcZEE3haECZEPb5EwTDbtsjPCSI',
    appId: '1:905140505558:android:64d11f9f38b7ec15613277',
    messagingSenderId: '905140505558',
    projectId: 'campus-companion-9691b',
    storageBucket: 'campus-companion-9691b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsOb-DpcZEE3haECZEPb5EwTDbtsjPCSI',
    appId: '1:905140505558:ios:64d11f9f38b7ec15613277',
    messagingSenderId: '905140505558',
    projectId: 'campus-companion-9691b',
    storageBucket: 'campus-companion-9691b.firebasestorage.app',
    iosBundleId: 'com.example.kare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsOb-DpcZEE3haECZEPb5EwTDbtsjPCSI',
    appId: '1:905140505558:macos:64d11f9f38b7ec15613277',
    messagingSenderId: '905140505558',
    projectId: 'campus-companion-9691b',
    storageBucket: 'campus-companion-9691b.firebasestorage.app',
    iosBundleId: 'com.example.kare',
  );
}
